---
micronaut:
  application:
    name: rental-agency
  http:
    services:
      price-calculator:
        urls:
          - https://rental-calculator-rlhwc3imia-ew.a.run.app

app.initial-car:
  AA-123-VV:
    brand: Renault
    model: Capture
    category: SUV
  BB-456-UU:
    brand: Ford
    model: Focus
    category: SUV

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    packages-to-scan:
      - 'com.stacklabs.micronaut.workshop.agency'

---
datasources.default: {}
